lints.workspace = true

[package]
name = "gix-traverse"
version = "0.54.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.82"
autotests = false

[lib]
doctest = false

[features]
## Enable support for the SHA-1 hash by enabling the respective feature in the `gix-hash` crate.
sha1 = ["gix-hash/sha1"]

[dependencies]
gix-hash = { version = "^0.22.1", path = "../gix-hash" }
gix-object = { version = "^0.57.0", path = "../gix-object" }
gix-date = { version = "^0.15.0", path = "../gix-date" }
gix-hashtable = { version = "^0.12.0", path = "../gix-hashtable" }
gix-revwalk = { version = "^0.28.0", path = "../gix-revwalk" }
gix-commitgraph = { version = "^0.34.0", path = "../gix-commitgraph" }
smallvec = "1.15.1"
thiserror = "2.0.18"
bitflags = "2"

[dev-dependencies]
gix-hash = { path = "../gix-hash", features = ["sha1"] }

[package.metadata.docs.rs]
features = ["sha1"]
