lints.workspace = true

[package]
name = "gix-worktree-state"
version = "0.27.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project implementing setting the worktree to a particular state"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.82"
autotests = false

[lib]
doctest = false

[features]
## Enable support for the SHA-1 hash by forwarding the feature to dependencies.
sha1 = ["gix-filter/sha1", "gix-index/sha1", "gix-object/sha1", "gix-worktree/sha1"]

[dependencies]
gix-worktree = { version = "^0.49.0", path = "../gix-worktree", default-features = false, features = ["attributes"] }
gix-index = { version = "^0.48.0", path = "../gix-index" }
gix-fs = { version = "^0.19.1", path = "../gix-fs" }
gix-object = { version = "^0.57.0", path = "../gix-object" }
gix-path = { version = "^0.11.1", path = "../gix-path" }
gix-features = { version = "^0.46.1", path = "../gix-features" }
gix-filter = { version = "^0.27.0", path = "../gix-filter" }

io-close = "0.3.7"
thiserror = "2.0.18"
bstr = { version = "1.12.0", default-features = false }

[dev-dependencies]
gix-worktree-state = { path = ".", features = ["sha1"] }

[package.metadata.docs.rs]
features = ["sha1"]
