lints.workspace = true

[package]
name = "gix-worktree-stream"
version = "0.29.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "generate a byte-stream from a git-tree"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.82"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[features]
## Enable support for the SHA-1 hash by forwarding the feature to dependencies.
sha1 = ["gix-filter/sha1", "gix-hash/sha1", "gix-object/sha1", "gix-traverse/sha1"]

[dependencies]
gix-features = { version = "^0.46.1", path = "../gix-features", features = ["progress", "io-pipe"] }
gix-hash = { version = "^0.22.1", path = "../gix-hash" }
gix-object = { version = "^0.57.0", path = "../gix-object" }
gix-attributes = { version = "^0.31.0", path = "../gix-attributes" }
gix-filter = { version = "^0.27.0", path = "../gix-filter" }
gix-traverse = { version = "^0.54.0", path = "../gix-traverse" }
gix-fs = { version = "^0.19.1", path = "../gix-fs" }
gix-path = { version = "^0.11.1", path = "../gix-path" }

gix-error = { version = "^0.2.0", path = "../gix-error" }
parking_lot = "0.12.4"

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
gix-odb = { path = "../gix-odb" }
gix-worktree = { path = "../gix-worktree", default-features = false, features = ["attributes"] }

[package.metadata.docs.rs]
features = ["sha1"]
